-- Sentinel live product - Supabase schema
--
-- Generated by inspecting the current in-memory model:
--   backend/app/live.py       (LiveSession, NurseState, PendingEvent)
--   backend/app/incidents.py  (Incident, IncidentManager)
--   backend/app/live_api.py   (the HTTP shapes/status values actually used)
--
-- Scope: ONLY the live product (login -> shift setup -> command center ->
-- nurse POV -> Manual/Auto Mode). Simulation Mode (FIFO/Greedy/Sentinel
-- comparison, app/simulate.py) is stateless per-request and intentionally
-- has no tables here.
--
-- This script only creates schema. No app code has been changed to use it
-- yet - the in-memory `_sessions` dict in app/live.py is still authoritative
-- until the integration pass.

BEGIN;

-- ============================================================================
-- shifts
-- One row per LiveSession. `status` only ever observes "active" in the
-- current code (no endpoint transitions it yet) but the field already
-- exists on the session, so it's included with room for "completed" later.
-- ============================================================================

CREATE TABLE shifts (
    id          BIGSERIAL PRIMARY KEY,
    shift_id    TEXT NOT NULL UNIQUE,              -- e.g. "SHIFT1b7cda6a" - the public id the API returns
    total_beds  INTEGER NOT NULL CHECK (total_beds > 0),
    status      TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed')),
    mode        TEXT NOT NULL DEFAULT 'auto' CHECK (mode IN ('auto', 'manual')),
    seed        INTEGER NOT NULL,                  -- IncidentManager/session RNG seed - not the RNG state itself
    started_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- nurses
-- One row per nurse for the shift. This is the ONLY place nurse<->incident
-- assignment is tracked - Incident itself carries no nurse reference; the
-- API derives it by looking up which nurse currently points at it.
-- ============================================================================

CREATE TABLE nurses (
    id                   BIGSERIAL PRIMARY KEY,
    nurse_id             TEXT NOT NULL UNIQUE,      -- e.g. "N7b30ea9a"
    shift_id             TEXT NOT NULL REFERENCES shifts (shift_id) ON DELETE CASCADE,
    name                 TEXT NOT NULL,
    role                 TEXT NOT NULL,
    status               TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'assigned', 'busy')),
    current_room         TEXT                       -- set only once START is pressed (workflow-derived, not tracked GPS)
    -- assigned_incident_id added below, once `incidents` exists - a plain
    -- TEXT column, not a formal FK (see the comment where it's added)
);

-- ============================================================================
-- pending_events
-- A raw incoming event awaiting a grade (Sentinel's suggestion in Auto Mode,
-- or the coordinator's pick in Manual Mode) before it becomes an Incident.
-- `vitals` mirrors PatientState exactly (app/severity.py) - NULL for a
-- technical/sensor-noise event, which has no physiology behind it at all.
-- ============================================================================

CREATE TABLE pending_events (
    id                      BIGSERIAL PRIMARY KEY,
    event_id                TEXT NOT NULL UNIQUE,   -- e.g. "EVT94c34cb3"
    shift_id                TEXT NOT NULL REFERENCES shifts (shift_id) ON DELETE CASCADE,
    room                    TEXT NOT NULL,
    patient_id              TEXT NOT NULL,          -- == room today (no real location tracking), kept as its own field
    technical               BOOLEAN NOT NULL DEFAULT FALSE,

    -- Shape: {"heart_rate": int, "oxygen_saturation": float,
    --         "systolic_bp": int, "respiratory_rate": int,
    --         "deterioration_rate": float}
    vitals                  JSONB,

    suggested_incident_type TEXT,
    suggested_severity      SMALLINT CHECK (suggested_severity BETWEEN 1 AND 10),
    status                  TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved')),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- incidents
-- The actual clinical work item - Sentinel's consolidated, aging-aware unit
-- of work (app/incidents.py:Incident). There is deliberately no separate
-- "tasks" table: severity, assignment eligibility, status, and timestamps
-- already live entirely on Incident in the real code.
--
-- `escalation_windows_checked` mirrors the private Incident._windows_checked
-- - the minimum bookkeeping needed so a restart doesn't re-roll starvation
-- windows that already happened. The RNG itself is never persisted.
-- ============================================================================

CREATE TABLE incidents (
    id                          BIGSERIAL PRIMARY KEY,
    -- "INC1", "INC2", ... is a per-IncidentManager counter that RESTARTS AT 1
    -- for every shift (each LiveSession gets its own fresh IncidentManager) -
    -- so incident_id is only unique WITHIN a shift, never globally. Hence
    -- UNIQUE (shift_id, incident_id) below instead of a bare UNIQUE here.
    incident_id                 TEXT NOT NULL,           -- e.g. "INC1" - preserved as-is, not replaced with a UUID
    shift_id                    TEXT NOT NULL REFERENCES shifts (shift_id) ON DELETE CASCADE,

    patient_id                  TEXT NOT NULL,
    room                        TEXT NOT NULL,
    incident_type                TEXT NOT NULL,          -- e.g. "LOW_SPO2", "SENSOR_DISCONNECT" - open-ended, not an enum

    initial_severity             SMALLINT NOT NULL CHECK (initial_severity BETWEEN 1 AND 10),
    current_severity             SMALLINT NOT NULL CHECK (current_severity BETWEEN 1 AND 10),
    peak_severity                SMALLINT NOT NULL CHECK (peak_severity BETWEEN 1 AND 10),

    first_seen                   TIMESTAMPTZ NOT NULL,
    last_seen                    TIMESTAMPTZ NOT NULL,
    repeat_count                 INTEGER NOT NULL DEFAULT 1 CHECK (repeat_count >= 1),

    status                        TEXT NOT NULL DEFAULT 'waiting' CHECK (status IN ('waiting', 'in_progress', 'resolved')),
    service_time                  DOUBLE PRECISION,       -- minutes; NULL until dispatched ("goal minutes" in the UI)

    severity_change_reason        TEXT NOT NULL DEFAULT 'none' CHECK (severity_change_reason IN ('physiology', 'starvation', 'none')),
    escalation_count              INTEGER NOT NULL DEFAULT 0 CHECK (escalation_count >= 0),
    escalation_windows_checked    INTEGER NOT NULL DEFAULT 0 CHECK (escalation_windows_checked >= 0),

    dispatched_at                 TIMESTAMPTZ,
    resolved_at                   TIMESTAMPTZ,

    -- incident_id is per-shift, not global (see comment above) - this is
    -- its real uniqueness boundary.
    UNIQUE (shift_id, incident_id)
);

-- At most one non-resolved incident per (patient_id, incident_type) PER
-- SHIFT - this is exactly the invariant IncidentManager._active enforces in
-- Python (each shift's IncidentManager is independent). patient_id is
-- currently == room, and every shift numbers rooms the same way starting at
-- "101" (see app/workload.py and the live product's floor grid), so two
-- different shifts routinely produce the same (patient_id, incident_type)
-- pair - shift_id has to be part of the key or shift B couldn't open an
-- incident in "its" room 101 while shift A still has one active in the
-- literal same-named room. A resolved incident recurring later legitimately
-- gets a NEW row (see
-- tests/test_incidents.py::test_resolved_incident_recurring_creates_new_incident),
-- so this is a PARTIAL unique index, not a plain one.
CREATE UNIQUE INDEX idx_incidents_active_key
    ON incidents (shift_id, patient_id, incident_type)
    WHERE status <> 'resolved';

-- Nurse -> incident assignment. No formal FK: incident_id alone isn't
-- unique (it's scoped by shift_id - see above), and a composite FK
-- (shift_id, assigned_incident_id) -> incidents (shift_id, incident_id)
-- is more relational-purity than a HackMIT timeline calls for tonight.
-- The app layer (app/live.py) already fully owns both sides of this write
-- and never assigns across shifts - add the composite FK later if desired.
ALTER TABLE nurses
    ADD COLUMN assigned_incident_id TEXT;

-- ============================================================================
-- Indexes for the query patterns the app actually needs
-- ============================================================================

CREATE INDEX idx_nurses_shift ON nurses (shift_id);
CREATE INDEX idx_pending_events_shift ON pending_events (shift_id);
CREATE INDEX idx_pending_events_shift_status ON pending_events (shift_id, status);
CREATE INDEX idx_incidents_shift ON incidents (shift_id);

-- Mirrors scheduler.pick_sentinel: highest current_severity first, oldest
-- first_seen breaks ties - exactly what "who's next" needs to query fast.
CREATE INDEX idx_incidents_dispatch_order
    ON incidents (shift_id, status, current_severity DESC, first_seen ASC);

COMMIT;

-- ============================================================================
-- Row Level Security
--
-- Supabase enables RLS by default on every new table, with zero policies -
-- i.e. deny-all. Without this block, every write from app/db_sync.py fails
-- with "new row violates row-level security policy" (error 42501).
--
-- This isn't a security hole to patch around: the actual trust boundary in
-- this app is the FastAPI backend, not Supabase. The browser never talks to
-- Supabase directly - only to FastAPI, using the publishable/anon key from
-- server-side code (backend/.env). RLS exists to protect untrusted direct
-- client access, which doesn't happen here, so disabling it is the correct
-- call for this architecture, not a shortcut.
--
-- (If a future browser-facing Supabase use case appears, re-enable RLS on
-- that path specifically rather than turning it back on globally here.)
-- ============================================================================

BEGIN;

ALTER TABLE shifts DISABLE ROW LEVEL SECURITY;
ALTER TABLE nurses DISABLE ROW LEVEL SECURITY;
ALTER TABLE pending_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE incidents DISABLE ROW LEVEL SECURITY;

COMMIT;
